### PR TITLE
Update 2021

### LINKED ISSUE #49: 2019/2021 PSID
Hi,
thank you for the amazing package.
I was wondering if the package will also include the latest 2019 and 2021 surveys? (I saw it includes the 2019 individual survey, but I could not find the Family survey).
Thank you very much

### PR DESCRIPTION
**Pull request by shdoron1**
Updated buildpanel and makeids to incorporate the latest PSID 2021 file and variable numbers (resolves #49).

### CODE REVIEW

**Comment by shdoron1** [comment]
By the way I LOVE this package. Thank you so much for creating it!

**Comment by floswald** [comment]
Hey!
Thanks for the PR, LGTM!
You know that getting those numbers right is the main thing of the package, so let me ask quickly whether you have tested this out and it seems to work? 
I'd love to have a formal way to test a PR like that but I can't think of one. 

Thanks again!

**Comment by shdoron1** [comment]
Hi Florian,

Yes I tested it and it seemed to download all the 2021 data. I'm sure there are more formal ways to test a PR like this but I also have no idea what it is!

Thanks again for this amazing package!!

**Comment by kaseyzapatka** [comment]
I just used @shdoron1 updates to pull the 2021 wave and it seemed to work for me. Thanks for all your hard work creating the package @floswald, and for this addition @shdoron1!

**Comment by floswald** [comment]
Thanks a lot both!

**Pull request merged**
