### PR TITLE
Update makeids.r

### PR DESCRIPTION
**Pull request by AGaillardTSE**
Update (this time it works) including 2019 wave.

### CODE REVIEW

**Comment by floswald** [comment]
All the other PRs can be closed? Please close those yourself.

**Comment by AGaillardTSE** [comment]
> All the other PRs can be closed? Please close those yourself.

Done.

**Comment by AGaillardTSE** [comment]
> All the other PRs can be closed? Please close those yourself.

done, you can merge the two remaining pull requests (build and makeids), if you want. Btw, thanks for this very helpful package!

**Comment by floswald** [comment]
thanks!

**Pull request merged**
